---
<<<<<<< HEAD
title: "Covid-19 Italy"
author: "Alessio Passalacqua"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
=======
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
>>>>>>> 77ddc691c5339f6af2f47a4079f38c80760acae9
---

```{r setup, include=FALSE}
library(flexdashboard)
```

<<<<<<< HEAD
Sidebar {.sidebar}
=======================================================================


```{r global, include=FALSE}
library(highcharter)
library(gtrendsR)
library(lubridate)
library(dplyr)
library(stringr)
library(viridisLite)
library(forecast)
library(DT)
```


```{r}
thm <- 
  hc_theme(
    colors = c("#1a6ecc", "#434348", "#90ed7d"),
    chart = list(
      backgroundColor = "transparent",
      style = list(fontFamily = "Source Sans Pro")),
    xAxis = list( gridLineWidth = 1)
  )

# map_ita <- readRDS("map_ita_json.RDS")
```

&nbsp;
<hr />
<p style="text-align: center;">by <a href="https://www.linkedin.com/in/alessiopassalacqua/">Alessio Passalacqua</a></p>
<p style="text-align: center;"><span style="color: #808080;"><em>alessio.passalacqua@gmail.com</em></span></p>

<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- Add font awesome icons -->
<p style="text-align: center;">
    <a href="https://twitter.com/alessiopassah2o" class="fa fa-twitter"></a>
    <a href="https://www.linkedin.com/in/alessiopassalacqua/" class="fa fa-linkedin"></a>
    <a href="https://github.com/alessiopassalacqua" class="fa fa-github"></a>
</p>

&nbsp;


Dashboard
=======================================================================

Column {data-width=600}
-----------------------------------------------------------------------


=======
Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

>>>>>>> 77ddc691c5339f6af2f47a4079f38c80760acae9
### Chart B

```{r}

```

<<<<<<< HEAD

Column {width=300}
-----------------------------------------------------------------------

=======
>>>>>>> 77ddc691c5339f6af2f47a4079f38c80760acae9
### Chart C

```{r}

```


<<<<<<< HEAD


Column {width=400}
-----------------------------------------------------------------------

### Chart D

```{r}

```


Download Data
=======================================================================

Row {data-height=1200}
-------------------------------------

```{r}

```

=======
>>>>>>> 77ddc691c5339f6af2f47a4079f38c80760acae9
